version: "3"
services:
  web:
    image: schogini/swarm-demo-8181
    environment:
     - NODE_NAME={{.Node.Hostname}}
     - NODE_IP={{.Service.Name}}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "8080:8181"
    networks:
      - webnet
  redis:
    image: redis:alpine
    networks:
      - webnet

networks:
  webnet:
